version: "3"

services:
  mc:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      DISABLE_HEALTHCHECK: "TRUE"
      EULA: "TRUE"
      MOTD: "Docker - Minecraft Server"
      MEMORY: "2G"
    volumes:
      - minecraft-data:/data

volumes:
  minecraft-data: